// ============================================================
// PRODUCT CATALOG — the only file you edit to change what the
// store sells.
//
// For each product:
//   1. Source it on CJ Dropshipping (cjdropshipping.com), prefer
//      US-warehouse listings, note the real all-in cost.
//   2. Create a Stripe Payment Link at the retail price and paste
//      the URL into `stripeLink`. Buttons say "Coming soon" until
//      you do.
//   3. Replace `image` with a real supplier photo (download from
//      the CJ listing into assets/img/, e.g. "assets/img/glove.jpg").
//      Until then the site shows the built-in illustration.
//   4. `rating`/`ratingCount`: OPTIONAL. Only fill these with the
//      real rating from your supplier's listing (these commodity
//      products usually have thousands of reviews). Leave null and
//      no stars are shown — never invent numbers.
// ============================================================

const STORE = {
  name: "PawHaven",
  tagline: "Clever gear for happier pets",
  supportEmail: "support@yourdomain.com", // change me
  currency: "$",
};

const PRODUCTS = [
  {
    active: true,
    id: "grooming-glove",
    name: "Pet Grooming Mitt",
    category: "Grooming",
    price: 17.99, compareAt: 24.99, cost: 5.49,
    badge: "Best Seller",
    image: "assets/img/photos/grooming-glove.jpg",
    imageFallback: "assets/img/grooming-glove.svg",
    gallery: ["assets/img/photos/grooming-glove.jpg", "assets/img/photos/grooming-glove-life.jpg"],
    rating: null, ratingCount: null,
    short: "Pet your dog or cat — the mitt lifts loose fur as you go.",
    description: "Slip it on and pet as usual. The textured deshedding mitt lifts and traps loose fur while your pet just thinks it's getting love. Works on dogs, cats and rabbits with long, short or curly coats — then the collected fur peels away in one piece.",
    bullets: ["Gentle enough for daily use — most pets think it's petting", "One size fits all, hand-washable", "Ships free from our US warehouse — arrives in 3–8 days"],
    stripeLink: "https://buy.stripe.com/00w9ATa77asU0Bx7bJ4ow00",
  },
  {
    active: true,
    id: "self-cleaning-brush",
    name: "Self-Cleaning Slicker Brush",
    category: "Grooming",
    price: 22.99, compareAt: 29.99, cost: 10.79,
    badge: "",
    image: "assets/img/photos/self-cleaning-brush.jpg",
    imageFallback: "assets/img/self-cleaning-brush.svg",
    gallery: ["assets/img/photos/self-cleaning-brush.jpg", "assets/img/photos/self-cleaning-brush-life.jpg"],
    rating: null, ratingCount: null,
    short: "One click retracts the bristles — collected fur falls right off.",
    description: "Fine bent-wire bristles reach the undercoat without scratching skin. Press the button when done: bristles retract and the fur drops off in one pad.",
    bullets: ["Push-button self-cleaning mechanism", "Rounded tips, safe for sensitive skin", "Free US shipping, 7–12 day delivery"],
    stripeLink: "https://buy.stripe.com/00w8wP4MN0Skesn7bJ4ow01",
  },
  {
    active: false, // pulled: see docs/SUPPLIERS.md
    id: "nail-grinder",
    name: "Whisper-Quiet Nail Grinder",
    category: "Grooming",
    price: 21.99, compareAt: 29.99, cost: 10.54,
    badge: "",
    image: "assets/img/nail-grinder.svg",
    imageFallback: "assets/img/nail-grinder.svg",
    rating: null, ratingCount: null,
    short: "USB-rechargeable, low-vibration — trims nails without the clipper panic.",
    description: "Diamond-bit grinder files nails smoothly instead of squeezing them. Low noise and vibration keep anxious pets calm. Two speeds, three port sizes for small to large breeds.",
    bullets: ["Quieter than standard grinders — under 40db", "USB-C rechargeable, 6hr runtime", "Free US shipping, 7–12 day delivery"],
    stripeLink: "https://buy.stripe.com/cNidR91AB9oQckfgMj4ow02",
  },
  {
    active: true,
    id: "slow-feeder",
    name: "Anti-Gulp Slow Feeder Bowl",
    category: "Feeding",
    price: 19.99, compareAt: 26.99, cost: 9.3,
    badge: "",
    image: "assets/img/photos/slow-feeder.jpg",
    imageFallback: "assets/img/slow-feeder.svg",
    gallery: ["assets/img/photos/slow-feeder.jpg", "assets/img/photos/slow-feeder-life.jpg"],
    rating: null, ratingCount: null,
    short: "Maze design slows fast eaters by up to 10x — better digestion, less bloat.",
    description: "Vets recommend slow feeders for dogs that inhale their food. The maze pattern turns mealtime into a puzzle, reducing bloat, vomiting and boredom. Non-slip base.",
    bullets: ["Food-grade, dishwasher-safe material", "Non-slip rubber base", "Free US shipping, 7–12 day delivery"],
    stripeLink: "https://buy.stripe.com/dRmdR97YZbwY5VR7bJ4ow03",
  },
  {
    active: false, // pulled: see docs/SUPPLIERS.md
    id: "lick-mat",
    name: "Calming Lick Mat",
    category: "Feeding",
    price: 13.99, compareAt: 18.99, cost: 10.98,
    badge: "",
    image: "assets/img/lick-mat.svg",
    imageFallback: "assets/img/lick-mat.svg",
    rating: null, ratingCount: null,
    short: "Spread peanut butter, buy yourself 20 calm minutes. Bath-time hack included.",
    description: "Licking is naturally soothing for dogs and cats. Textured surface holds spreads and slows them down — suction backing sticks to the bathtub wall for stress-free wash time.",
    bullets: ["Two textures, dishwasher safe", "Suction backing sticks to tubs and floors", "Free US shipping, 7–12 day delivery"],
    stripeLink: "https://buy.stripe.com/fZufZhdjj0Sk2JF0Nl4ow04",
  },
  {
    active: true,
    id: "water-bottle",
    name: "Portable Dog Water Bottle",
    category: "Walks",
    price: 19.99, compareAt: 26.99, cost: 9.44,
    badge: "",
    image: "assets/img/photos/water-bottle.jpg",
    imageFallback: "assets/img/water-bottle.svg",
    gallery: ["assets/img/photos/water-bottle.jpg", "assets/img/photos/water-bottle-life.jpg"],
    rating: null, ratingCount: null,
    short: "One-hand press fills the trough; unused water drains back. No more cupped hands.",
    description: "Leak-proof bottle with a built-in drinking trough. Press to fill, release to drain the extra back in — nothing wasted, nothing spilled in your bag.",
    bullets: ["19oz, leak-proof lock switch", "Food-grade, BPA-free", "Free US shipping, 7–12 day delivery"],
    stripeLink: "https://buy.stripe.com/8x23cv3IJ44w3NJ2Vt4ow05",
  },
  {
    active: true,
    id: "led-collar",
    name: "USB LED Safety Collar",
    category: "Walks",
    price: 16.99, compareAt: 22.99, cost: 7.28,
    badge: "",
    image: "assets/img/photos/led-collar.jpg",
    imageFallback: "assets/img/led-collar.svg",
    gallery: ["assets/img/photos/led-collar.jpg", "assets/img/photos/led-collar-life.jpg"],
    rating: null, ratingCount: null,
    short: "Makes your dog visible from 500m on night walks. Charges via USB.",
    description: "Three light modes keep your dog visible to cars and cyclists after dark. A 15-minute charge lasts up to 8 hours. Cuttable strip fits any neck size.",
    bullets: ["Visible up to 500m at night", "USB rechargeable — no coin batteries", "Free US shipping, 7–12 day delivery"],
    stripeLink: "https://buy.stripe.com/aFabJ13IJasU9830Nl4ow06",
  },
  {
    active: true,
    id: "seatbelt-tether",
    name: "Dog Car Seatbelt Tether",
    category: "Walks",
    price: 14.99, compareAt: 19.99, cost: 5.86,
    badge: "",
    image: "assets/img/photos/seatbelt-tether.jpg",
    imageFallback: "assets/img/seatbelt-tether.svg",
    gallery: ["assets/img/photos/seatbelt-tether.jpg", "assets/img/photos/seatbelt-tether-life.jpg"],
    rating: null, ratingCount: null,
    short: "Clips into any seatbelt buckle — keeps your co-pilot safe and off your lap.",
    description: "Heavy-duty nylon tether clicks into the standard seatbelt receiver and clips to any harness. Elastic buffer absorbs sudden stops. Adjustable 21–30 inches.",
    bullets: ["Fits standard seatbelt buckles", "Use with a harness, never a collar", "Free US shipping, 7–12 day delivery"],
    stripeLink: "https://buy.stripe.com/cNifZh6UVbwYfwr53B4ow07",
  },
  {
    active: false, // pulled: see docs/SUPPLIERS.md
    id: "paw-cleaner",
    name: "Portable Paw Cleaner Cup",
    category: "Walks",
    price: 16.99, compareAt: 22.99, cost: 37.21,
    badge: "",
    image: "assets/img/paw-cleaner.svg",
    imageFallback: "assets/img/paw-cleaner.svg",
    rating: null, ratingCount: null,
    short: "Dunk, twist, done — muddy paws cleaned at the door in seconds.",
    description: "Soft silicone bristles inside a spill-resistant cup. Add a little water, dip each paw, twist gently — mud stays in the cup, not on your floors.",
    bullets: ["Gentle silicone bristles", "Splits apart for easy rinsing", "Free US shipping, 7–12 day delivery"],
    stripeLink: "https://buy.stripe.com/eVqcN5gvv1Wo0BxbrZ4ow08",
  },
  {
    active: true,
    id: "hair-roller",
    name: "2-in-1 Reusable Pet Hair Roller",
    category: "Home",
    price: 21.99, compareAt: 27.99, cost: 7.85,
    badge: "TikTok Famous",
    image: "assets/img/photos/hair-roller.jpg",
    imageFallback: "assets/img/hair-roller.svg",
    gallery: ["assets/img/photos/hair-roller.jpg", "assets/img/photos/hair-roller-life.jpg"],
    rating: null, ratingCount: null,
    short: "Roll it over sofas and car seats — the chamber traps the fur, empty it with a click.",
    description: "The reusable roller that made 'fur-covered couch' videos famous. Roll it over sofas, beds and car seats and the chamber traps the hair — open the lid, dump it out, done. This 2-in-1 set includes a full-size roller for furniture plus a portable mini for clothes and the car. Nothing to replace, ever.",
    bullets: ["100% reusable — no sticky refills to buy", "Full-size roller + portable mini included", "Free US shipping, 7–12 day delivery"],
    stripeLink: "https://buy.stripe.com/28E28rfrr1Wo5VRbrZ4ow09",
  },
  {
    active: true,
    id: "snuffle-mat",
    name: "Interactive Snuffle Mat",
    category: "Play",
    price: 24.99, compareAt: 34.99, cost: 11.99,
    badge: "High Margin",
    image: "assets/img/photos/snuffle-mat.jpg",
    imageFallback: "assets/img/snuffle-mat.svg",
    gallery: ["assets/img/photos/snuffle-mat.jpg", "assets/img/photos/snuffle-mat-life.jpg"],
    rating: null, ratingCount: null,
    short: "Hides treats in fleece folds — 15 minutes of sniffing tires a dog like an hour of walking.",
    description: "Scatter kibble into the fleece folds and let your dog forage. Nosework is deeply tiring for dogs — trainers use snuffle mats to calm anxious and high-energy pups.",
    bullets: ["Great for anxious or high-energy dogs", "Machine washable, non-slip backing", "Free US shipping, 7–12 day delivery"],
    stripeLink: "https://buy.stripe.com/bJefZha777gIbgbeEb4ow0a",
  },
  {
    active: true,
    id: "cat-teaser",
    name: "Feather Wand Cat Teaser Set",
    category: "Play",
    price: 17.99, compareAt: 23.99, cost: 10.6,
    badge: "",
    image: "assets/img/photos/cat-teaser.jpg",
    imageFallback: "assets/img/cat-teaser.svg",
    gallery: ["assets/img/photos/cat-teaser.jpg", "assets/img/photos/cat-teaser-life.jpg"],
    rating: null, ratingCount: null,
    short: "Telescoping wand + 5 swap-on feather lures. Indoor cats' favorite cardio.",
    description: "Extends to 39 inches so you can play from the couch. Five interchangeable lures (feathers, worm, fish) keep the hunt fresh — rotation is the secret to a cat that never gets bored of it.",
    bullets: ["Telescopes from 15 to 39 inches", "5 replaceable lures included", "Free US shipping, 7–12 day delivery"],
    stripeLink: "https://buy.stripe.com/5kQ7sLdjj0Sk98367F4ow0b",
  },
];
